Fix armv6-vfp build
Do some minor updates necessary for gingerbread, mostly
deleting unused variables to fix these:

cc1: warnings being treated as errors
dalvik/vm/mterp/out/InterpC-armv6-vfp.c: In function 'dvmMterpDumpArmRegs':
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1232: error: unused variable 'glue'
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1235: error: unused variable 'method'
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1227: error: unused variable 'dvmAsmInstructionStart'

and rebuild everything

Change-Id: Ibedc61c8c90ab6b1f65ffe966d32afd1d9b2211d