Update patch set 1
Patch Set 1:

just to report this patch is not enough on korg/master

... -DOMAP_ENHANCEMENT -DTARGET_OMAP3 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -DNDEBUG -g -Wstrict-aliasing=2 -finline-functions -fno-inline-functions-called-once -fgcse-after-reload -frerun-cse-after-loop -frename-registers -DNDEBUG -UDEBUG  -O2 -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300   -fstrict-aliasing -Wstrict-aliasing=2 -fno-align-jumps -Wall -Wextra -Wno-unused-parameter -DARCH_VARIANT=\"armv7-a-neon\" -DDVM_SHOW_EXCEPTION=1 -DWITH_JIT -DWITH_HPROF=1 -Werror -UNDEBUG -DDEBUG=1 -DLOG_NDEBUG=1 -DWITH_DALVIK_ASSERT -DWITH_JIT_TUNING -DANDROID_SMP=0     -MD -o out/target/product/jordan/obj/SHARED_LIBRARIES/libdvm_assert_intermediates/alloc/Heap.o dalvik/vm/alloc/Heap.c


cc1: warnings being treated as errors
dalvik/vm/alloc/Heap.c: In function 'dvmCollectGarbageInternal':
dalvik/vm/alloc/Heap.c:918: error: unused variable 'isSmall'
dalvik/vm/alloc/Heap.c:935: error: unused variable 'isSmall'
make: *** [out/target/product/jordan/obj/SHARED_LIBRARIES/libdvm_assert_intermediates/alloc/Heap.o] Error 1

Patch-set: 1